import { chromium, devices } from 'playwright';
import { ARTIFACTS, BASE_URL, ok, ORIGIN, skipRecovery, sql } from './helpers.mjs';
const S=ARTIFACTS, URL=BASE_URL;
const b = await chromium.launch({ channel: 'chromium' });
const ctx = await b.newContext({ ...devices['Pixel 7'] });
const p = await ctx.newPage(); const errs=[]; p.on('pageerror', e=>errs.push(e.message)); p.on('dialog', d=>d.accept());
await p.addInitScript(()=>{ window.__vib=[]; navigator.vibrate = (x)=>{ window.__vib.push(x); return true; }; });
await p.goto(URL, { waitUntil: 'networkidle' });
await p.getByPlaceholder(/Código \(mínimo/).fill('clave-segura-1'); await p.getByPlaceholder('Repite el código').fill('clave-segura-1');
await p.getByRole('button',{name:'Crear código'}).click(); await skipRecovery(p); await p.getByRole('heading',{name:'Inicio'}).waitFor();
const alertBox = p.getByRole('alertdialog');
const add = async (amount, cat) => { await p.getByRole('button',{name:'Gasto'}).first().click(); await p.getByPlaceholder('0').fill(amount); await p.getByRole('dialog').getByRole('button',{name:new RegExp(cat)}).click(); await p.getByRole('button',{name:'Guardar'}).click(); await p.waitForTimeout(300); };
// tope 400.000 con aviso previo al 80 %
await p.getByLabel('Definir tope').click(); await p.locator('.budget input[inputmode=decimal]').fill('400.000');
ok(await p.getByRole('switch',{name:/Avisarme cuando me pase/}).isChecked(), 'aviso al pasarse activado por defecto');
await p.locator('.budget').getByRole('button',{name:'80 %'}).click();
await p.locator('.budget form').getByRole('button',{name:'Guardar'}).click();
await add('300.000','Vivienda');
ok(await alertBox.count()===0, '75 %: sin aviso');
await add('25.000','Comida');
ok(await alertBox.isVisible() && /Llevas el 81 % de tu presupuesto/.test(await alertBox.textContent()), 'cruza 80 %: aviso previo');
ok(/Te quedan \$75\.000/.test(await alertBox.textContent()), 'aviso previo dice cuánto queda');
await p.getByRole('button',{name:'Entendido'}).click();
await add('10.000','Comida');
ok(await alertBox.count()===0, 'otro gasto dentro del mismo nivel: no repite el aviso');
await add('70.000','Compras');
const t = await alertBox.textContent();
ok(/Estás por sobre tu presupuesto/.test(t) && /\$405\.000/.test(t) && /Te pasaste por \$5\.000/.test(t), 'al pasarse: alerta con monto y exceso');
ok((await p.evaluate(()=>window.__vib.filter((x)=>x!==30))).length===2, 'el teléfono vibra en cada aviso (además del toque corto al guardar)');
await p.waitForTimeout(250); await p.screenshot({ path: S+'/alert-over.png' });
await p.getByRole('button',{name:'Ver presupuesto'}).click();
ok(await alertBox.count()===0 && await p.locator('.budget-status.over').isVisible(), '"Ver presupuesto" cierra y muestra la barra en rojo');
await add('1.000','Comida');
ok(await alertBox.count()===0, 'ya sobre el tope: no molesta con cada gasto nuevo');
// borrar y volver a pasar → avisa de nuevo
await p.getByRole('navigation').getByRole('button',{name:'Historial'}).click();
await p.locator('.row', {hasText:'Compras'}).first().click(); await p.getByRole('button',{name:'Eliminar'}).click();
await p.getByRole('navigation').getByRole('button',{name:'Inicio'}).click();
await add('80.000','Compras');
ok(await alertBox.isVisible(), 'volver a cruzar el tope avisa otra vez');
await p.getByRole('button',{name:'Entendido'}).click();
// subir tope y bajarlo por debajo del gasto
await p.getByLabel('Cambiar tope').click(); await p.locator('.budget input[inputmode=decimal]').fill('1.000.000'); await p.locator('.budget form').getByRole('button',{name:'Guardar'}).click();
ok(await alertBox.count()===0, 'subir el tope: sin aviso');
await p.getByLabel('Cambiar tope').click(); await p.locator('.budget input[inputmode=decimal]').fill('300.000'); await p.locator('.budget form').getByRole('button',{name:'Guardar'}).click();
ok(await alertBox.isVisible(), 'bajar el tope por debajo de lo gastado: avisa');
await p.getByRole('button',{name:'Entendido'}).click();
// desactivar
await p.getByLabel('Cambiar tope').click(); await p.getByRole('switch',{name:/Avisarme cuando me pase/}).uncheck(); await p.locator('.budget form').getByRole('button',{name:'Cancelar'}).click();
await p.getByLabel('Cambiar tope').click(); await p.locator('.budget input[inputmode=decimal]').fill('1.000.000'); await p.locator('.budget form').getByRole('button',{name:'Guardar'}).click();
await p.getByLabel('Cambiar tope').click(); await p.locator('.budget input[inputmode=decimal]').fill('100.000'); await p.locator('.budget form').getByRole('button',{name:'Guardar'}).click();
ok(await alertBox.count()===0, 'con el aviso desactivado no aparece');
ok(errs.length===0, 'sin errores '+JSON.stringify(errs));
const ctx2 = await b.newContext({ ...devices['Pixel 7'], colorScheme:'dark' }); const q=await ctx2.newPage(); q.on('dialog', d=>d.accept());
await q.goto(URL, { waitUntil:'networkidle' }); await q.getByPlaceholder(/Código \(mínimo/).fill('clave-segura-1'); await q.getByPlaceholder('Repite el código').fill('clave-segura-1'); await q.getByRole('button',{name:'Crear código'}).click(); await skipRecovery(q); await q.getByRole('heading',{name:'Inicio'}).waitFor();
await q.getByLabel('Definir tope').click(); await q.locator('.budget input[inputmode=decimal]').fill('100.000'); await q.locator('.budget').getByRole('button',{name:'90 %'}).click(); await q.locator('.budget form').getByRole('button',{name:'Guardar'}).click();
await q.getByRole('button',{name:'Gasto'}).first().click(); await q.getByPlaceholder('0').fill('95.000'); await q.getByRole('dialog').getByRole('button',{name:/Comida/}).click(); await q.getByRole('button',{name:'Guardar'}).click();
await q.waitForTimeout(300); await q.screenshot({ path: S+'/alert-warn-dark.png' });
await b.close();
